routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'PagesController@index')->name('landing');
Route::get('/about', 'PagesController@about')->name('about');
Route::get('/contact', 'ContactController@contact')->name('contact');
Route::post('/contact', 'ContactController@saveContact')->name('contact.save');
Route::get('/teachers', 'TeacherProfileController@index')->name('teachers');
Route::get('/schools', 'SchoolController@index')->name('schools');
Route::get('/students', 'StudentController@index')->name('students');
Route::get('/jobs', 'JobController@index')->name('jobs');
Route::post('/search', 'SearchController@filter')->name('search');
Route::post('/schools', 'SearchController@school')->name('search.school');
Route::post('/jobs', 'SearchController@job')->name('search.job');
Route::post('/teachers', 'SearchController@teacher')->name('search.teacher');
Route::post('/newsletter', 'NewsletterController@store')->name('newsletter.store');

Route::get('/for-teachers', 'PagesController@teachers')->name('for_teachers');
Route::get('/for-schools', 'PagesController@schools')->name('for_schools');
Route::get('/for-guests', 'PagesController@guests')->name('for_guests');
Route::get('/for-job-seekers', 'PagesController@jobs')->name('for_jobs');
Route::get('/terms', 'PagesController@terms')->name('terms');
Route::get('/privacy', 'PagesController@privacy')->name('privacy');
Route::get('/support', 'PagesController@support')->name('support');
Route::get('/how', 'PagesController@how')->name('how');


Auth::routes(['verify' => true]);

Route::get('/profile', 'ProfileController@index')->name('profile');

Route::get('/verify/email', 'HomeController@verify')->name('verify.user');
Route::post('/profile/update', 'ProfileController@update')->name('profile.update');
Route::get('/teachers/{slug}', 'TeacherProfileController@show')->name('teachers.show');
Route::get('/schools/{slug}', 'SchoolController@show')->name('schools.show');
Route::get('/students/{slug}', 'StudentController@show')->name('students.show');
Route::get('/jobs/{slug}', 'JobController@show')->name('jobs.show');
Route::post('/comment', 'CommentController@store')->name('comment.store');
Route::get('/invitations', 'InvitationController@index')->name('invitations');
Route::get('/invitations/reply', 'InvitationController@reply')->name('invitation.reply');
Route::post('/invitations/replies', 'InvitationController@save')->name('invitation.save');
Route::get('/invitations/{id}', 'InvitationController@show')->name('invitations.show');
Route::get('/support-or-feedbacks/create', 'HomeController@supportCreate')->name('support.create');
Route::post('/support-or-feedbacks', 'HomeController@supportSave')->name('support.store');



Route::group(['prefix' => 'school', ['middleware' => ['school','admin','verified']]], function(){

      Route::get('/', 'SchoolController@index')->name('school');
      Route::get('/p/create', 'SchoolController@create')->name('school.profile');
      Route::post('/p', 'SchoolController@store')->name('school.store');
      Route::get('/p/{id}/edit', 'SchoolController@edit')->name('school.edit');
      Route::patch('/p/{id}', 'SchoolController@update')->name('school.update');
      Route::get('/job/create', 'JobController@create')->name('job.create');
      Route::post('/job', 'JobController@store')->name('job.store');
      Route::get('/myjobs', 'JobController@myjobposts')->name('job.post');
      Route::get('/job/{id}/edit','JobController@edit')->name('job.edit');
      Route::patch('/job/{id}','JobController@update')->name('job.update');
      Route::delete('/job/{id}', 'JobController@destroy')->name('job.delete');
      Route::get('/programs/create', 'ProgramController@create')->name('program.create');
      Route::post('/programs', 'ProgramController@store')->name('program.store');
      Route::get('/our-programs', 'ProgramController@index')->name('program.index');
      Route::get('/{id}/applicants', 'ApplicationController@show')->name('applicants.show');
      Route::get('/application/{id}/edit', 'ApplicationController@edit')->name('application.edit');
      Route::patch('/application/{id}', 'ApplicationController@update')->name('application.update');
      Route::get('/program/{id}/edit', 'ProgramController@edit')->name('program.edit');
      Route::patch('/our-programs/{id}', 'ProgramController@update')->name('program.update');
      Route::delete('/program/{id}', 'ProgramController@destroy')->name('program.delete');
      Route::get('/download/{id}','ApplicationController@download')->name('download.resume');
      Route::get('/invitations/create', 'InvitationController@create')->name('invitation.create');
      Route::post('/invitations', 'InvitationController@store')->name('invitation.store');
      Route::get('/branches/create', 'BrancheController@create')->name('branche.create');
      Route::post('/branches', 'BrancheController@store')->name('branche.store');
      Route::get('/branches/{id}/edit', 'BrancheController@edit')->name('branche.edit');
      Route::patch('/branches/{id}/', 'BrancheController@update')->name('branche.update');
      Route::delete('/branches/{id}', 'BrancheController@destroy')->name('branche.delete');


});


Route::group(['prefix' => 'student', ['middleware' => ['student','admin','verified']]], function(){
        
      Route::get('/','StudentController@index')->name('student');
      Route::get('/myposts','StudentController@mypost')->name('student.post');
      Route::get('/post/create','StudentController@create')->name('student.create');
      Route::post('/post','StudentController@store')->name('student.store');
      Route::get('/post/{id}/edit','StudentController@edit')->name('student.edit');
      Route::patch('/post/{id}','StudentController@update')->name('student.update');
      Route::delete('/post/{id}', 'StudentController@destroy')->name('student.delete');
      Route::get('/{id}/reviews','SchoolReviewController@create')->name('review.create');
      Route::post('{id}/reviews','SchoolReviewController@store')->name('review.store');
      Route::get('teacher/{id}/reviews','SchoolReviewController@createTeacher')->name('review.teacher');
      Route::post('teacher/{id}/reviews','SchoolReviewController@storeTeacher')->name('review.teacherStore'); 
     
});


Route::group(['prefix' => 'teacher', ['middleware' => ['teacher','admin','verified']]], function(){

     Route::get('/','TeacherProfileController@index')->name('teacher');
     Route::get('/p/create', 'TeacherProfileController@create')->name('teacher.profile');
     Route::post('/p', 'TeacherProfileController@store')->name('teacher.store');
     Route::get('/p/{id}/edit', 'TeacherProfileController@edit')->name('teacher.edit');
     Route::patch('/p/{id}', 'TeacherProfileController@update')->name('teacher.update');
     Route::get('{id}/application', 'ApplicationController@create')->name('application');
     Route::post('{id}/application', 'ApplicationController@store')->name('application.store');
     Route::get('my-application', 'ApplicationController@index')->name('myapplication');  
});

Route::middleware(['auth', 'admin'])->prefix('admin')->group(function () {

      Route::get('/','HomeController@index')->name('admin');
      Route::get('/users', 'UserController@index')->name('users');
      Route::get('/users/create', 'UserController@create')->name('users.create');
      Route::post('/user', 'UserController@store')->name('users.store');
      Route::delete('/users/{id}', 'UserController@destroy')->name('users.delete');
      Route::get('/users/profile/{id}/edit', 'UserController@edit')->name('users.edit');
      Route::patch('/users/profile/{id}', 'UserController@update')->name('users.update');
      Route::get('/profile/{id}/edit', 'UserController@profile')->name('profile.edit');
      Route::patch('/profile/{id}', 'UserController@updateProfile')->name('Userprofile.update');
      Route::get('/schools','SchoolController@schools')->name('schools.admin');
      Route::get('/teachers','TeacherProfileController@teachers')->name('teachers.admin');
      Route::get('/pages', 'ManagePageController@index')->name('pages');
      Route::get('/pages/create', 'ManagePageController@create')->name('pages.create');
      Route::post('/pages', 'ManagePageController@store')->name('pages.store');
      Route::get('/pages/{id}/edit', 'ManagePageController@edit')->name('pages.edit');
      Route::patch('/pages/{id}', 'ManagePageController@update')->name('pages.update');
      Route::delete('/pages/{id}', 'ManagePageController@destroy')->name('pages.delete');
      Route::get('user/support', 'HomeController@support')->name('support.admin');
      Route::get('user/support/{id}', 'HomeController@supportShow')->name('support.show');
      Route::get('messages', 'HomeController@messages')->name('messages');
      Route::get('messages/{id}', 'HomeController@message')->name('message'); 
});

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use App\Notifications\VerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use App\Notifications\PasswordReset;
use Illuminate\Contracts\Auth\CanResetPassword;
use App\Role;
use App\TeacherProfile;


class User extends Authenticatable implements MustVerifyEmail
{
    use Notifiable;

    /**
      * The password reset token.
      *
      * @var string
      */
    public $token;
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'profile_image'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function getImageAttribute()
    {
     return $this->profile_image; 
    }
    
    public function roles()
    {
     return $this->belongsToMany('App\Role');
    }

     public function hasAnyRole($role)
     {
     return null !== $this->roles()->where('name', $role)->first();
     }

    public function schoolReview()
    {
      return $this->hasMany('App\schoolReview');
    }
    public function teacherProfile()
    {
      return $this->hasOne('App\TeacherProfile');
    }

    public function hasTeacherProfile($user_id)
    {
      return null !== $this->teacherProfile()->where('user_id', $user_id)->first();
    }

    

    public function school()
    {
       return $this->hasOne('App\SchoolProfile');
    }

    public function hasSchoolProfile($user_id)
    {
      return null !== $this->school()->where('user_id', $user_id)->first();
    }

    public function post()
    {
       return $this->hasMany('App\StudentPost');
    }

    public function job()
    {
       return $this->hasMany('App\Job');
    }


    public function programs()
    {
        return $this->hasMany('App\Program');
    }

    /**
      * Send the password reset notification.
      *
      * @param  string  $token
      * @return void
      */
    public function sendPasswordResetNotification($token)
    {
        $this->notify(new PasswordReset($token));
    }

    /**
      * Send the email verification notification.
      *
      * @return void
      */
    public function sendEmailVerificationNotification()
    {
        $this->notify(new VerifyEmail); // my notification
    }
     
}

resources/views/admin/includes/header.blade.php
<!-- header start -->
<header class="ttr-header">
    <div class="ttr-header-wrapper">
        <!--sidebar menu toggler start -->
        <div class="ttr-toggle-sidebar ttr-material-button">
            <i class="ti-close ttr-open-icon"></i>
            <i class="ti-menu ttr-close-icon"></i>
        </div>
        <!--sidebar menu toggler end -->
        <!--logo start -->
        <div class="ttr-logo-box">
            <div>
                <a href="index.html" class="ttr-logo">
                    <img class="ttr-logo-mobile" alt="" src="{{ asset('assets/images/logo.png')}}" width="30" height="30">
                    <img class="ttr-logo-desktop" alt="" src="{{ asset('assets/images/logo.png')}}" width="160" height="27">
                </a>
            </div>
        </div>
        <!--logo end -->
        <div class="ttr-header-menu">
            <!-- header left menu start -->
            <ul class="ttr-header-navigation">
                <li>
                <a href="{{ url('/')}}" class="ttr-material-button ttr-submenu-toggle">Landing</a>
                </li>
                <li>
                    <a href="#" class="ttr-material-button ttr-submenu-toggle">MENU <i class="fa fa-angle-down"></i></a>
                    <div class="ttr-header-submenu">
                        <ul>
                            <li><a href="#">Teachers</a></li>
                            <li><a href="#">Schools</a></li>
                            <li><a href="#">Posts</a></li>
                            <li><a href="#">Jobs</a></li>
                            <li><a href="#">About</a></li>
                            <li><a href="#">Contact</a></li>
                        </ul>
                    </div>
                </li>
            </ul>
            <!-- header left menu end -->
        </div>
        <div class="ttr-header-right ttr-with-seperator">
            <!-- header right menu start -->
            <ul class="ttr-header-navigation">
                <li>
                    <a href="#" class="ttr-material-button ttr-submenu-toggle"><span class="ttr-user-avatar"><img alt="" src="{{ Auth::user()->image ? Auth::user()->image: url('https://img.icons8.com/officel/16/000000/user-male-skin-type-5.png') }}" width="32" height="32"></span></a>
                    <div class="ttr-header-submenu">
                        <ul>
                        <li><a href="{{ route('profile.edit', Auth::user()->id)}}">Mon profile</a></li>
                            <li><a href="{{ route('logout') }}" onclick="event.preventDefault();
                                                 document.getElementById('logout-form').submit();">se deconnecter</a></li>
                        </ul>
                          <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                    @csrf
                        </form>
                    </div>
                </li>
            </ul>
            <!-- header right menu end -->
        </div>
        <!--header search panel start -->
        <div class="ttr-search-bar">
            <form class="ttr-search-form">
                <div class="ttr-search-input-wrapper">
                    <input type="text" name="qq" placeholder="search something..." class="ttr-search-input">
                    <button type="submit" name="search" class="ttr-search-submit"><i class="ti-arrow-right"></i></button>
                </div>
                <span class="ttr-search-close ttr-search-toggle">
                    <i class="ti-close"></i>
                </span>
            </form>
        </div>
        <!--header search panel end -->
    </div>
</header>
<!-- header end -->

resources/views/admin/includes/sidebar.blade.php
	<!-- Left sidebar menu start -->
	<div class="ttr-sidebar">
		<div class="ttr-sidebar-wrapper content-scroll">
			<!-- side menu logo start -->
			<div class="ttr-sidebar-logo">
				<a href="#"><img alt="" src="{{ asset('assets/images/logo.png')}}" width="122" height="27"></a>
				<!-- <div class="ttr-sidebar-pin-button" title="Pin/Unpin Menu">
					<i class="material-icons ttr-fixed-icon">gps_fixed</i>
					<i class="material-icons ttr-not-fixed-icon">gps_not_fixed</i>
				</div> -->
				<div class="ttr-sidebar-toggle-button">
					<i class="ti-arrow-left"></i>
				</div>
			</div>
			<!-- side menu logo end -->
			<!-- sidebar menu start -->
			<nav class="ttr-sidebar-navi">
				<ul>
					<li>
						<a href="{{route('admin')}}" class="ttr-material-button">
							<span class="ttr-icon"><i class="ti-home"></i></span>
		                	<span class="ttr-label">Dashboard</span>
		                </a>
					</li>
					@if (Auth::check() && Auth::user()->hasAnyRole('admin'))
					<li>
				   <a href="#" class="ttr-material-button">
					   <span class="ttr-icon"><i class="ti-layout-accordion-list"></i></span>
					   <span class="ttr-label">Pages</span>
					   <span class="ttr-arrow-icon"><i class="fa fa-angle-down"></i></span>
				   </a>
				   <ul>
					   <li>
						   <a href="{{ route('pages')}}" class="ttr-material-button"><span class="ttr-label">Pages</span></a>
					   </li>
				   </ul>
			   </li>
			   <li>
				   <a href="{{ route('users') }}" class="ttr-material-button">
					   <span class="ttr-icon"><i class="ti-user"></i></span>
					   <span class="ttr-label">Users</span>
				   </a>
			   </li>
			   <li>
				<a href="{{ route('schools.admin') }}" class="ttr-material-button">
					<span class="ttr-icon"><i class="ti-folder"></i></span>
					<span class="ttr-label">Schools</span>
				</a>
				<li>
					<a href="{{ route('teachers.admin') }}" class="ttr-material-button">
						<span class="ttr-icon"><i class="ti-folder"></i></span>
						<span class="ttr-label">Teachers</span>
					</a>
				</li>
				<li>
					<a href="{{ route('messages') }}" class="ttr-material-button">
						<span class="ttr-icon"><i class="ti-email"></i></span>
						<span class="ttr-label">Messages</span>
					</a>
				</li>
				<li>
					<a href="{{ route('support.admin') }}" class="ttr-material-button">
						<span class="ttr-icon"><i class="ti-settings"></i></span>
						<span class="ttr-label">Feedbacks or Support</span>
					</a>
				</li>
			</li>
				@endif

					<li>
				</ul>
				<!-- sidebar menu end -->
			</nav>
			<!-- sidebar menu end -->
		</div>
	</div>
	<!-- Left sidebar menu end -->